trigger:
  - master
  - preview

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Windows
    displayName: Build and Test
    jobs:
      - job: Build
        displayName: Build and Test
        pool:
          vmImage: 'windows-latest'

        steps:
          - task: UseDotNet@2
            displayName: Setup 3.1.x .NET SDK
            inputs:
              packageType: 'sdk'
              version: '3.1.x'

          - task: UseDotNet@2
            displayName: Setup 5.0.x .NET SDKs
            inputs:
              packageType: 'sdk'
              version: '5.0.x'

          - task: UseDotNet@2
            displayName: Setup 6.0.x .NET SDKs
            inputs:
              packageType: 'sdk'
              version: '6.0.x'

          - task: UseDotNet@2
            displayName: Setup 7.0.x .NET SDKs
            inputs:
              packageType: 'sdk'
              version: '7.0.x'

          - task: UseDotNet@2
            displayName: Setup 8.0.x .NET SDKs
            inputs:
              packageType: 'sdk'
              version: '8.0.x'
              includePreviewVersions: true

          - task: UseDotNet@2
            displayName: Setup 9.0.x .NET SDKs
            inputs:
              packageType: 'sdk'
              version: '9.0.x'
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: Restore projects
            inputs:
              command: 'restore'
              feedsToUse: 'select'

          - task: DotNetCoreCLI@2
            displayName: Build projects
            inputs:
              command: 'build'
              arguments: '-c $(buildConfiguration) --no-restore'

          - task: DotNetCoreCLI@2
            displayName: Test projects
            inputs:
              command: 'test'
              arguments: '-c $(buildConfiguration) --no-build --no-restore --verbosity normal'
